export const dogBreeds= [
    { value: "Affenpinscher", show: "Affenpinscher" },
    { value: "Airedale Terrier", show: "Airedale Terrier" },
    { value: "Akita Inu", show: "Akita Inu" },
    { value: "Amstaff", show: "Amstaff" },
    { value: "Azawakh", show: "Azawakh" },
    { value: "Barbet", show: "Barbet" },
    { value: "Barzoi", show: "Barzoi" },
    { value: "Basenji", show: "Basenji" },
    { value: "Basset Artesien Norman", show: "Basset Artesien Norman" },
    { value: "Basset Griffon Vendeen", show: "Basset Griffon Vendeen" },
    { value: "Basset Hound", show: "Basset Hound" },
    { value: "Basset roscat de Bretania", show: "Basset roscat de Bretania" },
    { value: "Beagle", show: "Beagle" },
    { value: "Bearded", show: "Bearded" },
    { value: "Caine chinezesc cu creasta", show: "Caine chinezesc cu creasta" },
    { value: "Caine de Islanda", show: "Caine de Islanda" },
    { value: "Caine de apa portughez", show: "Caine de apa portughez" },
    { value: "Caine de cireada australian", show: "Caine de cireada australian" },
    { value: "Caine de munte de Pirinei", show: "Caine de munte de Pirinei" },
    { value: "Dalmatian", show: 'Dalmatian' }
];
export default dogBreeds;
// Rase de câini: https://www.infocaini.ro/rase-de-caini/
//     Affenpinscher, Airedale Terrier, Akita Inu, Amstaff, Azawakh,Barbet, Barzoi, Basenji, Basset Artesien Normand,
//     Basset Griffon Vendeen, Basset Hound, Basset roscat de Bretania, Beagle, Bearded, Caine chinezesc cu creasta,
//     Caine de Islanda, Caine de apa portughez, Caine de cireada australian, Caine de munte de Pirinei,
//     Dalmatian, Dandie Dinmont Terrier, Deerhound, Doberman, Dog German, Dog argentinian, Dog de Bordeaux, Drentse Patrijshond,
//     Elkhound norvegian, Epagneul Breton, Epagneul francez, Eurasian,
//     Field Spaniel, Fila Brasileiro, Fox Terrier,
//
//     Glen of Imaal terrier, Golden Retriever, Griffon de Bruxelles, Groenendael Ciobanesc belgian,
//     Hovaward, Husky siberian,
//     Keeshond, Kerry Blue Terrier, King Charles Spaniel, Komondor, Kuvasz,
//     Labrador Retriever, Laeken Ciobanesc belgian, Lakeland Terrier, Lapphound suedez, Lapphund finlandez, Leonberger, Lhasa Apso,